#!/usr/bin/env Rscript

if (file.exists("renv/activate.R")) {
  source("renv/activate.R")
}

library(AneuFinder)
library(optparse)
library(logger)
library(GenomicRanges)

## Fixed path to the variable-width reference BED
VARIABLE_WIDTH_REFERENCE <- "/nemo/project/proj-tracerX/working/VCAM1_GnT/DAQI/source/Aneufinder/mappability/normal_ref_sorted.bam.bed"

## CLI
option_list <- list(
  make_option(c("-i", "--input"), type = "character"),
  make_option(c("-o", "--output"), type = "character"),
  make_option(c("-b", "--blacklist"), type = "character", default = NULL),
  make_option(c("-m", "--method"), type = "character", default = "edivisive"),
  make_option(c("-s", "--binsize"), type = "integer", default = 1e6),
  make_option(c("-c", "--chromosomes"), type = "character", default = paste0("chr", c(1:22))),
  make_option(c("-n", "--numcpu"), type = "integer", default = 4),
  make_option(c("-p", "--cluster-plots"), type = "logical", default = TRUE),
  make_option(c("-r", "--reuse-existing"), type = "logical", default = FALSE),
  make_option(c("-g", "--gc-rds"), type = "character", default = NULL,
              help = "Shared GC template RDS generated by the pipeline. REQUIRED.")
)
opt <- parse_args(OptionParser(option_list = option_list))

run_aneufinder <- function() {
  normalize_bin_names <- function(x) {
    x <- sub("^binsize_1e\\+06$", "binsize_1000000", x)
    x <- sub("^0$", "binsize_1000000", x)
    x
  }
  deduplicate_bins <- function(grl) {
    names(grl) <- normalize_bin_names(names(grl))
    grl[!duplicated(names(grl))]
  }
  
  # hard fail if GC not provided
  if (is.null(opt$`gc-rds`)) {
    stop("You must provide --gc-rds pointing to the shared GC template .rds")
  }
  if (!file.exists(opt$`gc-rds`)) {
    stop(paste0("GC template file not found: ", opt$`gc-rds`))
  }
  set.seed(42)
  
  log_info("Starting AneuFinder analysis")
  log_info("Random seed set to 42")
  log_info(paste0("Input: ", opt$input))
  log_info(paste0("Output: ", opt$output))
  log_info(paste0("GC template: ", opt$`gc-rds`))
  
  if (!dir.exists(opt$input)) stop("Input directory not found: ", opt$input)
  
  bam_files <- list.files(opt$input, pattern = "\\.bam$", full.names = TRUE)
  if (length(bam_files) == 0) stop("No BAM files found in: ", opt$input)
  
  dir.create(opt$output, recursive = TRUE, showWarnings = FALSE)
  
  chromosomes <- unlist(strsplit(opt$chromosomes, ","))
  methods     <- unlist(strsplit(opt$method, ","))
  
  ## 1) Precompute variable width bins once from the big BED
  log_info("Precomputing variable width bins once from reference BED ...")
  ref_reads_ <- bed2GRanges(
    bedfile    = VARIABLE_WIDTH_REFERENCE,
    assembly   = "hg38",
    chromosomes = chromosomes,
    blacklist  = opt$blacklist
  )
  
  pre_bins_ <- variableWidthBins(
    reads       = ref_reads_,
    binsizes    = opt$binsize,
    chromosomes = chromosomes
  )
  
  ## 2) Load shared GC template (must exist)
  bins_gc_ <- readRDS(opt$`gc-rds`)
  if (inherits(bins_gc_, "GRanges")) {
    bins_gc_ <- GenomicRanges::GRangesList("0" = bins_gc_)
  }
  bins_gc_ <- deduplicate_bins(bins_gc_)
  
  # make model dirs up front
  for (m in methods) {
    dir.create(file.path(opt$output, "MODELS", paste0("method-", m)),
               recursive = TRUE, showWarnings = FALSE)
  }
  
  ## 3) Process BAMs
  for (bf in bam_files) {
    id_ <- tools::file_path_sans_ext(basename(bf))
    log_info(paste0("Processing ", id_))
    
    # bin using precomputed bins
    binned_ <- binReads(
      file           = bf,
      bins           = pre_bins_,
      blacklist      = opt$blacklist,
      assembly       = "hg38",
      save.as.RData  = FALSE,
      use.bamsignals = FALSE
    )
    
    # normalise to GRangesList without losing the original bin names
    if (inherits(binned_, "GRangesList")) {
      binned_obj_ <- binned_
    } else if (inherits(binned_, "GRanges")) {
      binned_obj_ <- GenomicRanges::GRangesList("binsize_1000000" = binned_)
    } else if (is.list(binned_)) {
      binned_obj_ <- GenomicRanges::GRangesList(binned_)
    } else {
      stop(
        paste0(
          "Unexpected binReads() output class: ",
          paste(class(binned_), collapse = ", ")
        )
      )
    }
    binned_obj_ <- deduplicate_bins(binned_obj_)
    
    common_bins_ <- intersect(names(binned_obj_), names(bins_gc_))
    if (length(common_bins_) == 0) {
      stop(
        paste0(
          "No matching bin names between sample bins (",
          paste(names(binned_obj_), collapse = ", "),
          ") and GC template bins (",
          paste(names(bins_gc_), collapse = ", "),
          ")."
        )
      )
    }
    
    binned_obj_ <- binned_obj_[common_bins_]
    bins_gc_sample_ <- bins_gc_[common_bins_]
    
    # GC correction with the shared GC template
    corrected_list_ <- correctGC(
      binned.data.list = list(binned_obj_),
      GC.BSgenome      = NULL,
      same.binsize     = TRUE,
      method           = "loess",
      bins             = bins_gc_sample_
    )
    binned_gc_obj_ <- corrected_list_[[1]]
    
    # CNV calling
    for (m in methods) {
      method_dir_ <- file.path(opt$output, "MODELS", paste0("method-", m))
      dir.create(method_dir_, recursive = TRUE, showWarnings = FALSE)
      
      model <- switch(
        m,
        "edivisive" = findCNVs(binned_gc_obj_, ID = id_, method = "edivisive"),
        "HMM"       = findCNVs(binned_gc_obj_, ID = id_, method = "HMM"),
        "dnacopy"   = findCNVs(binned_gc_obj_, ID = id_, method = "dnacopy"),
        stop(paste("Unknown method:", m))
      )
      save(model, file = file.path(method_dir_, paste0(id_, ".RData")))
    }
  }
  
  ## 4) Plotting (your block)
  if (isTRUE(opt$`cluster-plots`)) {
    for (m in methods) {
      method_dir <- file.path(opt$output, "MODELS", paste0("method-", m))
      if (!dir.exists(method_dir)) next
      
      rdata_files <- list.files(method_dir, pattern = "\\.RData$", full.names = TRUE)
      if (length(rdata_files) == 0) next

      profiles_pdf <- file.path(opt$output, paste0("profiles_", m, ".pdf"))
      grDevices::pdf(file = profiles_pdf, width = 12, height = 14)
      for (ifile in rdata_files) {
        tryCatch({
          obj_name <- load(ifile)
          model <- get(obj_name[1])
          p1 <- plot(model, type = "profile", plot.breakpoints = TRUE)
          p2 <- plot(model, type = "histogram")
          cowplt <- cowplot::plot_grid(p1, p2, ncol = 1, rel_heights = c(1.4, 1))
          print(cowplt)
        }, error = function(err) {
          log_warn(paste0("Could not create profile plot for ", basename(ifile), ": ", err$message))
        })
      }
      grDevices::dev.off()
      log_info(paste0("Profile plots written to: ", profiles_pdf))
      
      clus <- clusterByQuality(rdata_files)
      out_pdf <- file.path(opt$output, paste0("Genome_heatmap_cluster_1Mb_bins_", m, ".pdf"))
      heatmapGenomewideClusters(clus, file = out_pdf)
      log_info(paste0("Cluster heatmap written to: ", out_pdf))
    }
  }
  
  ## 5) Summary
  results_dir <- file.path(opt$output, "MODELS")
  if (dir.exists(results_dir)) {
    model_count  <- length(list.files(results_dir, pattern = "\\.RData$", recursive = TRUE))
    summary_file <- file.path(opt$output, "analysis_summary.txt")
    writeLines(c(
      "ANEUFINDER ANALYSIS SUMMARY",
      "===========================",
      paste0("Date: ", Sys.Date()),
      paste0("Input directory: ", opt$input),
      paste0("Total BAM files: ", length(bam_files)),
      paste0("Successful analyses: ", model_count),
      paste0("Methods used: ", paste(methods, collapse = ", ")),
      paste0("Bin size: ", format(opt$binsize, big.mark = ",")),
      paste0("Chromosomes: ", paste(chromosomes, collapse = ", ")),
      if (!is.null(opt$blacklist)) paste0("Blacklist: ", opt$blacklist) else NULL,
      paste0("Variable width reference: ", VARIABLE_WIDTH_REFERENCE),
      paste0("GC template: ", opt$`gc-rds`)
    ), summary_file)
    log_info(paste0("Summary written to: ", summary_file))
  }
}

if (!interactive()) {
  tryCatch(run_aneufinder(), error = function(e) {
    log_error(e$message)
    quit(status = 1)
  })
}
